apiVersion: v1
kind: ConfigMap
metadata:
  ########################################################################
  ########################################################################
  name: opsmx-services-demo-agent  ## REPLACE "demo-agent" agent-name
  ########################################################################
  ########################################################################
  labels:
    agent.opsmx.com/name: agent1
    agent.opsmx.com/role: agent
data:
  services.yaml: |
    services:
      - name: dev-jenkins
        type: jenkins
        enabled: true
        config:
          url: https://dev-jenkins.opsmx.com
          credentials:
            type: basic
            secretName: opsmxspin-jenkins
      - name: dev-jen-inline-pass
        type: jenkins
        enabled: true
        config:
          url: http://jenkins.opsmx.net:8181/jenkins/
          #credentials:
          #  type: basic
          #  username: b3BzbkZXY=
          #  password: QnVtYlYmVlQDEyMyQ=
      - name: demo-cluster
        type: kubernetes
        enabled: true
        namespaces:
        - name: ninja
          namespaces:
            - ninja-srini
            - ninja-yeshaswini
        - name: dev-ns
          namespaces:
            - ninja-susmitha
            - ninja-vamsi
      - name: dev-artifactory
        type: artifactory
        enabled: true
        config:
          url: https://artifactory.example.com/
          repo: example-repo-local
          credentials:
            type: basic
            secretName: opsmx-artifactory
      - name: dev-bitbucket
        type: bitbucket
        enabled: true
        config:
          url: https://bitbucket.org/
          credentials:
            type: basic
            secretName: opsmx-bitbucket
 
   
